"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { getUserDataClient, type UserDataExport } from "@/app/actions/getUserDataClient";
import { Loader2, Download, Database, FileAudio, FileText, CreditCard, ExternalLink } from "lucide-react";
import toast from "react-hot-toast";
import Link from "next/link";
import { useAuth } from "@/lib/firebase/auth-context";

export default function MyDataPage() {
  const { user } = useAuth();
  const [data, setData] = useState<UserDataExport | null>(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    if (user) {
      loadUserData();
    }
  }, [user]);

  const loadUserData = async () => {
    if (!user) return;

    setLoading(true);
    try {
      const result = await getUserDataClient(user.uid);
      if (result.success && result.data) {
        setData(result.data);
      } else {
        toast.error(result.error || "Error loading data");
      }
    } catch (error) {
      console.error("Error loading data:", error);
      toast.error("Error loading data");
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async () => {
    if (!data) return;

    setExporting(true);
    try {
      // Create GDPR-compliant export from current data
      const gdprExport = {
        exportDate: new Date().toISOString(),
        exportVersion: "1.0",

        userData: data.user
          ? {
              email: data.user.email,
              accountCreated: data.user.createdAt?.toDate?.()?.toISOString() || "",
              tier: data.user.tier || "free",
              subscriptionStatus: data.user.subscriptionStatus,
              quota: {
                monthly: data.user.quota.monthly,
                used: data.user.quota.used,
                resetAt: data.user.quota.resetAt?.toDate?.()?.toISOString(),
              },
              stripeCustomerId: data.user.stripeCustomerId,
            }
          : null,

        podcasts: data.podcasts.map((podcast) => ({
          id: podcast.id,
          fileName: podcast.fileName,
          fileSize: podcast.fileSize,
          uploadedAt: podcast.uploadedAt?.toDate?.()?.toISOString() || "",
          status: podcast.status,
          storagePath: podcast.storagePath,
          downloadUrl: podcast.downloadUrl,
          duration: podcast.duration,
          processingStartedAt: podcast.processingStartedAt?.toDate?.()?.toISOString(),
          processingCompletedAt: podcast.processingCompletedAt?.toDate?.()?.toISOString(),
          errorMessage: podcast.errorMessage,
        })),

        articles: data.articles.map((article) => ({
          id: article.id,
          title: article.title,
          slug: article.slug,
          createdAt: article.createdAt?.toDate?.()?.toISOString() || "",
          editedAt: article.editedAt?.toDate?.()?.toISOString(),
          contentMarkdown: article.contentMarkdown,
          metaDescription: article.metaDescription,
          keywords: article.keywords,
        })),

        subscriptions: data.subscriptions.map((subscription) => ({
          id: subscription.id,
          stripeSubscriptionId: subscription.stripeSubscriptionId,
          status: subscription.status,
          tier: subscription.tier,
          currentPeriodStart: subscription.currentPeriodStart?.toDate?.()?.toISOString() || "",
          currentPeriodEnd: subscription.currentPeriodEnd?.toDate?.()?.toISOString() || "",
          cancelAtPeriodEnd: subscription.cancelAtPeriodEnd,
        })),

        gdprInformation: {
          dataCategories: [
            {
              category: "Identification Data",
              description: "Data used to identify your account",
              fields: ["Email Address", "User ID", "Stripe Customer ID"],
            },
            {
              category: "Account Data",
              description: "Information about your account status",
              fields: ["Creation Date", "Subscription Tier", "Subscription Status", "Quota Usage"],
            },
            {
              category: "Content Data",
              description: "Content uploaded and generated by you",
              fields: ["Podcast Audio Files", "Generated Articles", "File Names", "Metadata"],
            },
            {
              category: "Financial Data",
              description: "Payment-related information",
              fields: ["Subscription Information", "Billing Periods", "Stripe References"],
            },
          ],
          processingPurposes: [
            "Account management and authentication",
            "Service provision (podcast-to-article conversion)",
            "Billing and subscription management",
            "Service improvement and error analysis",
          ],
          thirdPartyRecipients: [
            {
              name: "Google Cloud Platform",
              purpose: "Hosting and AI processing",
              dataShared: ["Audio Files", "User Data", "Generated Content"],
            },
            {
              name: "Stripe Inc.",
              purpose: "Payment processing",
              dataShared: ["Email Address", "Stripe Customer ID", "Subscription Information"],
            },
          ],
          retentionPolicy:
            "All data is stored until account deletion. After account deletion, all data will be completely deleted within 30 days.",
          userRights: [
            "Right to Access (Art. 15 GDPR) - This export function",
            "Right to Rectification (Art. 16 GDPR) - Contact info@echoscribes.com",
            "Right to Erasure (Art. 17 GDPR) - Available in account settings",
            "Right to Data Portability (Art. 20 GDPR) - This export function",
          ],
        },
      };

      // Create downloadable JSON file
      const blob = new Blob([JSON.stringify(gdprExport, null, 2)], {
        type: "application/json",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `echoscribe-daten-export-${new Date().toISOString().split("T")[0]}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast.success("Data successfully exported");
    } catch (error) {
      console.error("Export error:", error);
      toast.error("Error exporting data");
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!data || !data.user) {
    return (
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold">My Data</h1>
          <p className="text-muted-foreground mt-2">
            Your stored data could not be loaded.
          </p>
        </div>
      </div>
    );
  }

  const formatDate = (timestamp: any) => {
    if (!timestamp) return "N/A";
    const date = timestamp.toDate?.() || new Date(timestamp);
    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const formatBytes = (bytes: number) => {
    if (bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + " " + sizes[i];
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">My Data</h1>
          <p className="text-muted-foreground mt-2">
            View all your stored data in accordance with GDPR Art. 15
          </p>
        </div>
        <Button onClick={handleExport} disabled={exporting}>
          {exporting ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Exporting...
            </>
          ) : (
            <>
              <Download className="mr-2 h-4 w-4" />
              Export as JSON
            </>
          )}
        </Button>
      </div>

      {/* Profile Information */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Database className="h-5 w-5" />
            Profile Information
          </CardTitle>
          <CardDescription>Your account and identification data</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-medium text-muted-foreground">Email Address</label>
              <p className="text-sm mt-1">{data.user.email}</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">User ID</label>
              <p className="text-sm mt-1 font-mono text-xs">{data.user.id}</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Account Created</label>
              <p className="text-sm mt-1">{formatDate(data.user.createdAt)}</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Subscription Tier</label>
              <p className="text-sm mt-1 capitalize">{data.user.tier || "free"}</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Subscription Status</label>
              <p className="text-sm mt-1 capitalize">{data.user.subscriptionStatus}</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Quota Usage</label>
              <p className="text-sm mt-1">
                {data.user.quota.used} / {data.user.quota.monthly} used
              </p>
            </div>
            {data.user.stripeCustomerId && (
              <div>
                <label className="text-sm font-medium text-muted-foreground">Stripe Customer ID</label>
                <p className="text-sm mt-1 font-mono text-xs">{data.user.stripeCustomerId}</p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Podcasts */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileAudio className="h-5 w-5" />
            Podcasts ({data.podcasts.length})
          </CardTitle>
          <CardDescription>All audio files uploaded by you</CardDescription>
        </CardHeader>
        <CardContent>
          {data.podcasts.length === 0 ? (
            <p className="text-sm text-muted-foreground">No podcasts uploaded</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="border-b">
                  <tr>
                    <th className="text-left py-2 font-medium">File Name</th>
                    <th className="text-left py-2 font-medium">Size</th>
                    <th className="text-left py-2 font-medium">Status</th>
                    <th className="text-left py-2 font-medium">Uploaded</th>
                    <th className="text-left py-2 font-medium">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {data.podcasts.map((podcast) => (
                    <tr key={podcast.id} className="border-b">
                      <td className="py-3 max-w-xs truncate">{podcast.fileName}</td>
                      <td className="py-3">{formatBytes(podcast.fileSize)}</td>
                      <td className="py-3">
                        <span
                          className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${
                            podcast.status === "completed"
                              ? "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200"
                              : podcast.status === "error"
                              ? "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200"
                              : "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200"
                          }`}
                        >
                          {podcast.status}
                        </span>
                      </td>
                      <td className="py-3 text-muted-foreground">
                        {formatDate(podcast.uploadedAt)}
                      </td>
                      <td className="py-3">
                        {podcast.downloadUrl && (
                          <Button variant="ghost" size="sm" asChild>
                            <a href={podcast.downloadUrl} target="_blank" rel="noopener noreferrer">
                              <Download className="h-4 w-4" />
                            </a>
                          </Button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Articles */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Articles ({data.articles.length})
          </CardTitle>
          <CardDescription>All articles generated from your podcasts</CardDescription>
        </CardHeader>
        <CardContent>
          {data.articles.length === 0 ? (
            <p className="text-sm text-muted-foreground">No articles generated</p>
          ) : (
            <div className="space-y-3">
              {data.articles.map((article) => (
                <div
                  key={article.id}
                  className="flex items-start justify-between p-3 rounded-lg border bg-card hover:bg-accent/50 transition-colors"
                >
                  <div className="flex-1 min-w-0">
                    <h3 className="font-medium truncate">{article.title}</h3>
                    <p className="text-sm text-muted-foreground mt-1">
                      Created: {formatDate(article.createdAt)}
                    </p>
                    {article.metaDescription && (
                      <p className="text-sm text-muted-foreground mt-1 line-clamp-2">
                        {article.metaDescription}
                      </p>
                    )}
                  </div>
                  <Button variant="ghost" size="sm" asChild className="ml-4 shrink-0">
                    <Link href={`/dashboard/articles/${article.slug}`}>
                      <ExternalLink className="h-4 w-4" />
                    </Link>
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Subscriptions */}
      {data.subscriptions.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <CreditCard className="h-5 w-5" />
              Subscriptions ({data.subscriptions.length})
            </CardTitle>
            <CardDescription>Your subscription history and payment information</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {data.subscriptions.map((subscription) => (
                <div
                  key={subscription.id}
                  className="p-3 rounded-lg border bg-card"
                >
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-medium text-muted-foreground">Tier</label>
                      <p className="text-sm mt-1 capitalize">{subscription.tier || "N/A"}</p>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-muted-foreground">Status</label>
                      <p className="text-sm mt-1 capitalize">{subscription.status}</p>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-muted-foreground">Period</label>
                      <p className="text-sm mt-1">
                        {formatDate(subscription.currentPeriodStart)} -{" "}
                        {formatDate(subscription.currentPeriodEnd)}
                      </p>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-muted-foreground">Stripe-ID</label>
                      <p className="text-sm mt-1 font-mono text-xs truncate">
                        {subscription.stripeSubscriptionId}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* GDPR Information */}
      <Card>
        <CardHeader>
          <CardTitle>Data Processing & Your Rights</CardTitle>
          <CardDescription>Transparency according to GDPR</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="text-sm font-medium mb-2">Third-Party Providers</h3>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>• <strong>Google Cloud Platform:</strong> Hosting and storage</li>
              <li>• <strong>OpenAI:</strong> AI processing (transcription and article generation)</li>
              <li>• <strong>Stripe:</strong> Payment processing and subscription management</li>
            </ul>
          </div>

          <div>
            <h3 className="text-sm font-medium mb-2">Your GDPR Rights</h3>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>✓ <strong>Right to Access (Art. 15):</strong> This page</li>
              <li>✓ <strong>Right to Data Portability (Art. 20):</strong> JSON export function above</li>
              <li>✓ <strong>Right to Erasure (Art. 17):</strong> Available in{" "}
                <Link href="/dashboard/settings" className="underline">
                  Settings
                </Link>
              </li>
              <li>• <strong>Additional Rights:</strong> Contact info@echoscribes.com</li>
            </ul>
          </div>

          <div>
            <h3 className="text-sm font-medium mb-2">Retention Period</h3>
            <p className="text-sm text-muted-foreground">
              All data is stored until account deletion. After account deletion,
              complete data deletion occurs within 30 days.
            </p>
          </div>

          <div className="pt-4 border-t">
            <p className="text-xs text-muted-foreground">
              For more information, see our{" "}
              <Link href="/privacy" className="underline">
                Privacy Policy
              </Link>
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
